"""Initial migration: Create tables for weather ETL

Revision ID: 7394d65332b2
Revises: 
Create Date: 2026-03-04 15:25:19.944430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7394d65332b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clima',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=False),
    sa.Column('pais', sa.String(length=100), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('temperatura', sa.Float(), nullable=True),
    sa.Column('sensacion_termica', sa.Float(), nullable=True),
    sa.Column('humedad', sa.Integer(), nullable=True),
    sa.Column('presion', sa.Integer(), nullable=True),
    sa.Column('velocidad_viento', sa.Float(), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('fecha_extraccion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clima_id'), 'clima', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clima_id'), table_name='clima')
    op.drop_table('clima')
    # ### end Alembic commands ###
